import { Data, IProductInput} from '@/types'
import { toSlug } from './utils'

const products: IProductInput[] = [
  {
    name: 'Chitato',
    slug: toSlug('Chitato'),
    category: 'Snacks',
    images: ['/images/chitato-1.jpg', '/images/chitato-2.jpg'],
    tags: ['new-arrival'],
    isPublished: true,
    price: 3.5,
    listPrice: 0,
    brand: 'Chitato',
    avgRating: 4.5,
    numReviews: 15,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 0 },
      { rating: 3, count: 2 },
      { rating: 4, count: 6 },
      { rating: 5, count: 6 },
    ],
    numSales: 50,
    countInStock: 30,
    description: 'Delicious potato chips with unique flavors.',
    sizes: ['Regular', 'Large'],
    colors: ['Yellow', 'Green'],
    reviews: [],
  },
  {
    name: 'Lays',
    slug: toSlug('Lays'),
    category: 'Snacks',
    images: ['/images/lays-1.jpg', '/images/lays-2.jpg'],
    tags: ['popular'],
    isPublished: true,
    price: 2.8,
    listPrice: 0,
    brand: 'Lays',
    avgRating: 4.7,
    numReviews: 20,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 1 },
      { rating: 3, count: 3 },
      { rating: 4, count: 8 },
      { rating: 5, count: 8 },
    ],
    numSales: 70,
    countInStock: 40,
    description: 'Crispy and crunchy potato chips with a variety of flavors.',
    sizes: ['Snack', 'Family Size'],
    colors: ['Yellow', 'Blue'],
    reviews: [],
  },
  {
    name: 'Fanta',
    slug: toSlug('Fanta'),
    category: 'Drinks',
    images: ['/images/fanta-1.jpg', '/images/fanta-2.jpg'],
    tags: ['featured'],
    isPublished: true,
    price: 1.5,
    listPrice: 0,
    brand: 'Fanta',
    avgRating: 4.6,
    numReviews: 25,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 2 },
      { rating: 3, count: 4 },
      { rating: 4, count: 10 },
      { rating: 5, count: 9 },
    ],
    numSales: 60,
    countInStock: 50,
    description: 'Refreshing fruit-flavored soda.',
    sizes: ['Can', 'Bottle'],
    colors: ['Orange'],
    reviews: [],
  },
  {
    name: 'Ice Cream',
    slug: toSlug('Ice Cream'),
    category: 'Desserts',
    images: ['/images/ice-cream-1.jpg', '/images/ice-cream-2.jpg'],
    tags: ['treat'],
    isPublished: true,
    price: 4.5,
    listPrice: 0,
    brand: 'Ice Cream',
    avgRating: 4.8,
    numReviews: 18,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 2 },
      { rating: 4, count: 6 },
      { rating: 5, count: 10 },
    ],
    numSales: 45,
    countInStock: 25,
    description: 'Creamy and delicious ice cream in various flavors.',
    sizes: ['Small', 'Medium', 'Large'],
    colors: ['White', 'Chocolate', 'Strawberry'],
    reviews: [],
  },
  {
    name: 'Sayur Kol',
    slug: toSlug('Sayur Kol'),
    category: 'Vegetables',
    images: ['/images/sayur-kol-1.jpg', '/images/sayur-kol-2.jpg'],
    tags: ['fresh'],
    isPublished: true,
    price: 2.0,
    listPrice: 0,
    brand: 'Sayur Kol',
    avgRating: 4.3,
    numReviews: 10,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 1 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 2 },
    ],
    numSales: 30,
    countInStock: 40,
    description: 'Fresh cabbage, perfect for salads and cooking.',
    sizes: ['Bundle', 'Single'],
    colors: ['Green'],
    reviews: [],
  }  
]

const data: Data = {
  products,
    headerMenus: [
      {
        name: "Today's Deal",
        href: '/search?tag=todays-deal',
      },
      {
        name: 'New Arrivals',
        href: '/search?tag=new-arrival',
      },
      {
        name: 'Featured Products',
        href: '/search?tag=featured',
      },
      {
        name: 'Best Sellers',
        href: '/search?tag=best-seller',
      },
      {
        name: 'Browsing History',
        href: '/#browsing-history',
      },
      {
        name: 'Customer Service',
        href: '/page/customer-service',
      },
      {
        name: 'About Us',
        href: '/page/about-us',
      },
      {
        name: 'Help',
        href: '/page/help',
      },
    ],
    carousels: [
        {
          title: 'Most Popular Beverages For Sale',
          buttonCaption: 'Shop Now',
          image: '/images/banner3.jpg',
          url: '/search?category=Beverages',
          isPublished: true,
        },
        {
          title: 'Best Quality Products',
          buttonCaption: 'Shop Now',
          image: '/images/banner1.jpg',
          url: '/search?category=Products',
          isPublished: true,
        },
        {
          title: 'Best Snacks to Enjoy With Your Family',
          buttonCaption: 'See More',
          image: '/images/banner2.jpg',
          url: '/search?category=Snacks',
          isPublished: true,
        },
    ],
}    

export default data